# Generated by Django 2.2 on 2019-05-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requestforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameField', models.CharField(default=' ', max_length=200, verbose_name='Your First and Last Name')),
                ('emailField', models.EmailField(default=' ', max_length=254, verbose_name='A valid email address, please.')),
                ('domainCheckField', models.BooleanField(blank=True, default=True)),
                ('urlField', models.URLField(default=' ', verbose_name='Your website')),
                ('descriptionField', models.TextField(default=' ', max_length=20000)),
            ],
        ),
    ]
